services:
  analysis-service:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: analysis_service/Dockerfile.cpu
      args:
        BUILDPLATFORM: linux/arm64
    image: meekyolo/analysis-service:arm64-latest
    container_name: analysis-service
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - model_data:/app/data/models
      - ./data:/app/data
      - ./logs:/app/logs
      - ./results:/app/results
      - ./config:/app/analysis_service/config
    environment:
      - ANALYSIS_SERVICE_ENV=production
      - MODEL_SERVICE_HOST=model-service
      - DEVICE=cpu
      - ANALYSIS__confidence=0.2
    networks:
      - meekyolo-net
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'

volumes:
  model_data:
    name: meekyolo_model_data
    external: true

networks:
  meekyolo-net:
    name: meekyolo-net
    external: false 