services:
  analysis-service:
    build:
      context: ..  # 改回上级目录
      dockerfile: analysis_service/Dockerfile.gpu
    image: meekyolo/analysis-service:gpu-latest
    container_name: analysis-service
    restart: unless-stopped
    runtime: nvidia  # 使用 NVIDIA 运行时
    ports:
      - "8002:8002"
    volumes:
      - model_data:/app/data/models
      - ./data:/app/data
      - ./logs:/app/logs
      - ./results:/app/results
      - ../config:/app/config
    environment:
      - ANALYSIS_SERVICE_ENV=production
      - MODEL_SERVICE_HOST=model-service
      - NVIDIA_VISIBLE_DEVICES=all
      - DEVICE=cuda
      - CONFIG_PATH=/app/config/config.yaml
    networks:
      - meekyolo-net
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 8G  # GPU 版本通常需要更多内存
          cpus: '4'   # GPU 版本通常需要更多 CPU
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true

volumes:
  model_data:
    name: meekyolo_model_data
    external: true

networks:
  meekyolo-net:
    name: meekyolo-net
    external: true 