# 服务基础配置
PROJECT_NAME: "MeekYolo Analysis Service"
VERSION: "2.0.0"

# 服务配置
SERVICES:
  host: "0.0.0.0"
  port: 8002

# 通信模式配置
COMMUNICATION:
  mode: "mqtt"  # http 或 mqtt，决定使用哪种通信方式

# MQTT配置
MQTT:
  broker_host: "mqtt.yingzhu.net"
  broker_port: 1883
  username: "yolo"
  password: "yolo"
  topic_prefix: "meek/"  # 注意：标准格式为 meek/
  qos: 1
  keepalive: 60
  reconnect_interval: 5  # 断线重连间隔(秒)
  node_id: ""  # 节点ID，留空自动使用MAC地址
  service_type: "analysis"  # 节点类型

# Redis配置
REDIS:
  host: "localhost"
  port: 6379
  password: "123456"
  db: 0
  max_connections: 50
  socket_timeout: 5
  retry_on_timeout: true

# 模型服务配置
MODEL_SERVICE:
  url: "http://localhost:8003"
  api_prefix: "/api/v1"

# 分析配置
ANALYSIS:
  confidence: 0.2
  iou: 0.45
  max_det: 300
  device: "auto"
  
  # 新增配置
  analyze_interval: 1  # 默认分析间隔
  alarm_interval: 60   # 默认报警间隔
  random_interval: [0, 0]  # 默认随机间隔范围
  push_interval: 1     # 默认推送间隔

# 存储配置
STORAGE:
  base_dir: "data"
  model_dir: "models"
  temp_dir: "temp"
  max_size: 10737418240  # 10GB

# 输出配置
OUTPUT:
  save_dir: "results"
  save_txt: false
  save_img: true
  return_base64: true 

# 任务队列配置
TASK_QUEUE:
  max_concurrent: 30  # 最大并发任务数
  max_retries: 3    # 最大重试次数
  retry_delay: 5    # 重试延迟(秒)
  result_ttl: 7200  # 结果缓存时间(秒)
  cleanup_interval: 3600  # 清理间隔(秒) 

DEBUG:
  enabled: true  # 设置为 true 开启调试模式
  log_level: "DEBUG"  # 日志级别：DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "logs/debug.log"  # 日志文件路径
  log_rotation: "1 day"  # 日志轮转周期
  log_retention: "7 days"  # 日志保留时间